# Тензоры в PyTorch
<img src="./images/pytorch_logo.png" width=240>

[*Тензор*](https://pytorch.org/docs/stable/tensors.html) - специализированная структура данных наподобие матриц и массивов. 

В *PyTorch* тензоры хранят входные и выходные данные моделей, а также их параметры (веса).

#### Установка PyTorch 2.0

In [ ]:
# PyTorch 2.0 + CUDA 11.8:
! pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu118
    
# PyTorch 2.0 nightly + CUDA 12.1:
! pip3 install torch torchvision --pre --index-url https://download.pytorch.org/whl/nightly/cu121 

#### Импортируем необходимые библиотеки

In [1]:
import numpy as np
import torch
print (torch.cuda.is_available())
torch.__version__

True


'2.2.2+cu121'

### 1. Инициализация тензоров

In [2]:
# Инициализация из данных:
my_data = [[1,2,3], [4,5,6], [7,8,9]]
print (my_data, '\n')

my_tensor = torch.tensor(my_data)
print (my_tensor)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [3]:
# Инициализация из NymPy array:
np_array = np.array(my_data)
print (np_array, '\n')

my_tensor = torch.from_numpy(np_array)
print (my_tensor)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)


In [4]:
# Инициализация из другого тензора:
my_ones = torch.ones_like(my_tensor) # свойства сохраняются
print(my_ones, '\n')

my_rand = torch.rand_like(my_tensor, dtype=torch.float) # переопределяем тип хранимых данных
print(my_rand)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32) 

tensor([[0.7793, 0.7899, 0.1579],
        [0.5170, 0.3712, 0.9397],
        [0.3119, 0.0944, 0.0674]])


In [5]:
# Инициализация с определением размерности тензора:
shape = (4,2,)
print (torch.rand(shape))
print (torch.ones(shape))
print (torch.zeros(shape))

tensor([[0.8415, 0.8940],
        [0.2113, 0.8028],
        [0.6719, 0.0167],
        [0.9210, 0.8458]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### 2. Атрибуты тензоров

In [6]:
my_tensor = torch.rand(3,4,5)

print(f"Форма: {my_tensor.shape}")
print(f"Тип данных: {my_tensor.dtype}")
print(f"Девайс где хранятся данные: {my_tensor.device}")

Форма: torch.Size([3, 4, 5])
Тип данных: torch.float32
Девайс где хранятся данные: cpu


### 3. Операции над тензорами
[Список операций в PyTorch](https://pytorch.org/docs/stable/torch.html)

In [ ]:
# Перемещаем тензор на GPU:
my_tensor = torch.rand(size=(3,4))
if torch.cuda.is_available():
    my_tensor = my_tensor.to("cuda:0")
    
print (my_tensor)

In [ ]:
# Операции indexing и slicing:
print(f"Первая строка: {my_tensor[0]}")
print(f"Первый столбец: {my_tensor[:, 0]}")
print(f"Последний столбец: {my_tensor[..., -1]}")

my_tensor = my_tensor.to("cpu")
my_tensor[:,1] = 0     # присваиваем константу 0 второму столбцу
print (my_tensor)

In [ ]:
# Конкатенация тензоров:
join_tensor = torch.cat([my_tensor, my_tensor, my_tensor], dim=0)
print(join_tensor.shape)
print(join_tensor)

In [ ]:
# Арифметические операции - перемножение матрица:
y1 = my_tensor @ my_tensor.T
y2 = my_tensor.matmul(my_tensor.T)
y3 = torch.rand_like(my_tensor)
torch.matmul(my_tensor, my_tensor.T, out=y3)
print ('y1:', y1,'\ny2:', y2,'\ny3:',y3)

# Арифметические операции - поэлементное перемножение:
z1 = my_tensor * my_tensor
z2 = my_tensor.mul(my_tensor)
z3 = torch.rand_like(my_tensor)
torch.mul(my_tensor, my_tensor, out=z3)
print ('z1:', z1,'\nz2:', z2,'\nz3:',z3)

In [ ]:
# Одноэлементные тензоры:
result = my_tensor.sum()   # суммируем все элементы тензора
value = result.item()      # приводим тензор к Python numerical value
print(value, type(value))
print (result, type(result))

### 4. PyTorch тензоры и NumPy массивы:

In [ ]:
# Tensor -> NumPy array:
t = torch.ones(5)
n = t.numpy()

t[1] = -6
print(t, t.shape, t.dtype)
print(n, n.shape, n.dtype)

In [ ]:
# NumPy array -> Tensor:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 6, out=n)
print(t, t.shape, t.dtype)
print(n, n.shape, n.dtype)